name: Generate and Upload PDF

on:
  push:
    branches:
      - main

jobs:
  generate_and_upload_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache LaTeX Dependencies
        uses: actions/cache@v2
        with:
          path: /usr/share/texlive
          key: latex-dependencies

      - name: Install LaTeX Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y texlive-xetex texlive-fonts-recommended

      - name: Cache Pandoc
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/pandoc
          key: pandoc

      - name: Install Pandoc
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-linux-amd64.tar.gz
          tar xvzf pandoc-2.14.1-linux-amd64.tar.gz
          sudo mv pandoc-2.14.1/bin/pandoc /usr/local/bin/
          rm -rf pandoc-2.14.1*

      - name: Convert Markdown to PDF
        run: pandoc README.md -o resume.pdf

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your.email@example.com"

      - name: Add PDF to Repository
        run: |
          git checkout -b pdf
          git add resume.pdf
          git commit -m "Add generated PDF"
          git push origin pdf
