name: Generate PDF

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # You might need to install the necessary tools for PDF generation.
        # For example, if you're using pandoc, you can install it with:
        # apt-get -y install pandoc

    - name: Generate PDF
      run: |
        # Convert your Markdown file (resume.md) to PDF using the appropriate tool.
        # For example, if you're using pandoc, the command would be:
        # pandoc -s resume.md -o resume.pdf

    - name: Save PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume-pdf
        path: resume.pdf
